#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print(np.__version__)

1.23.5


#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
np.empty(10)

array([4.82199710e-310, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       1.29061927e+248, 9.14066849e-043, 4.90483236e-062, 6.87031033e-091,
       2.10938144e-052, 2.59475340e-029])

#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
np.empty(10).size * np.empty(10).itemsize
print(np.empty(10).nbytes)

80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
np.add?

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
arr = np.zeros(10,dtype=int)
arr[4] = 1
arr

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
arr = np.arange(start = 10,stop = 50)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
arr = np.array([1,2,3,4])
arr[0],arr[-1] = arr[-1],arr[0]
arr

array([4, 2, 3, 1])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
np.nonzero(np.array([1,2,0,0,4,0]))

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
np.random.randint(0,27,27).reshape(3,3,3)

array([[[16,  6,  5],
        [21, 26, 16],
        [10,  1,  7]],

       [[13,  3, 15],
        [17, 14,  9],
        [ 4, 13,  5]],

       [[25,  8, 23],
        [15, 20,  6],
        [18,  5,  3]]])

In [ ]:
np.random.rand(3,3,3)

array([[[0.13331599, 0.65597992, 0.73327585],
        [0.30442549, 0.256661  , 0.79524919],
        [0.10609867, 0.8858027 , 0.04558077]],

       [[0.92324581, 0.74014564, 0.77510779],
        [0.19396411, 0.31603801, 0.1816225 ],
        [0.80741969, 0.08061024, 0.91535261]],

       [[0.53613607, 0.86175282, 0.06915545],
        [0.56488249, 0.25829951, 0.61267486],
        [0.37860654, 0.08495679, 0.07946088]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
x = np.random.randint(0,1000,100).reshape(10,10)
print(np.amax(x))
print(np.amin(x))
x

967
0


array([[829, 397, 907, 265, 134, 863, 431, 174,  85, 939],
       [377, 526, 442, 255, 701, 398, 173, 648, 232, 691],
       [171, 967, 801, 535, 628, 637, 735, 172, 819, 769],
       [205, 622, 533, 736, 744, 929,  86,  63, 589, 388],
       [139, 750, 458, 926, 512,  28, 825, 441, 757, 697],
       [  0, 214, 720, 921, 854, 886, 239, 667, 202, 405],
       [957, 461, 212, 107, 278, 397, 573,  14, 457, 518],
       [715, 528, 793, 600, 202, 285, 733, 122, 283, 951],
       [616, 523, 487, 800, 347, 506, 792, 786, 457,   1],
       [321, 700, 426, 531, 920, 164, 130, 411, 587, 958]])

In [ ]:
x = np.random.rand(10,10)
print(np.amax(x))
print(np.amin(x))
x

0.9953000492782056
0.0069621228327467755


array([[0.71575168, 0.51998592, 0.39460826, 0.49188614, 0.73858123,
        0.49583411, 0.55708638, 0.88404248, 0.44047388, 0.50404745],
       [0.30880419, 0.15638557, 0.20268976, 0.11286766, 0.99415853,
        0.74228335, 0.25775174, 0.39393753, 0.64037659, 0.03472608],
       [0.52842624, 0.58832207, 0.66302933, 0.26376081, 0.42560377,
        0.08871742, 0.64660874, 0.32370282, 0.86962171, 0.34399924],
       [0.19941569, 0.33575135, 0.44191602, 0.5232963 , 0.40163173,
        0.90822691, 0.31239681, 0.21508231, 0.68388466, 0.59868902],
       [0.76820827, 0.00696212, 0.58143268, 0.34927465, 0.15012509,
        0.29379557, 0.76059599, 0.0525201 , 0.44993596, 0.59522701],
       [0.16317451, 0.32743668, 0.58616958, 0.55055296, 0.1822711 ,
        0.97405142, 0.54449478, 0.01324884, 0.26908652, 0.27916681],
       [0.90711251, 0.40709587, 0.17673491, 0.77595853, 0.50845808,
        0.56179182, 0.65042599, 0.17617118, 0.81871818, 0.49324347],
       [0.7375429 , 0.34239218, 0.2178889

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
x = np.random.randint(0,1000,30)
print(np.mean(x))
x

531.9333333333333


array([182, 558,  92, 784, 283, 666, 701, 301, 322, 637, 275, 589, 706,
       215,  23, 780, 746, 943, 503, 389, 860, 341, 800, 979, 525, 399,
       673,  48, 978, 660])

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
a = np.ones((10,10))
a[1:-1,1:-1]=0
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
a = np.ones((5,5))
a = np.pad(a,2)
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
1st --> nan
2nd --> False
3rd --> False
4th --> nan
5th --> True
6th --> True

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:
x = np.zeros(25).reshape(5,5)

for i in range(1,5):
  x[i,i-1] = i

print(x)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


In [ ]:
x = np.zeros(25).reshape(5,5)
x[1,0] = 1
x[2,1] = 2
x[3,2] = 3
x[4,3] = 4

print(x)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
x = np.zeros((8,8),dtype=int)

for i in range(8):
  if i < 7:
    x[i,i+1] = 1
  if i < 5:
    x[i,i+3] = 1
  if i < 3:
    x[i,i+5] = 1
  if i < 1:
    x[i,i+7] = 1
  if i > 0:
    x[i,i-1] = 1
  if i > 2:
    x[i,i-3] = 1
  if i > 4:
    x[i,i-5] = 1
  if i > 6:
    x[i,0] = 1

print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
matrix = np.zeros((8, 8), dtype=int)

matrix[1::2, ::2] = 1
matrix[::2, 1::2] = 1

print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [ ]:
shape = (6, 7, 8)

element_number = 100

z = element_number // (shape[1] * shape[2])
remainder = (element_number - 1) % (shape[1] * shape[2])
y = remainder // shape[2]
x = remainder % shape[2]

print((x, y, z))

(3, 5, 1)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
arr = np.array([[1,0],[0,1]])

x = np.tile(arr,(4,4))

print(x)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [ ]:
np.random.randint(0,1000,25).reshape(5,5)

array([[887, 427, 276, 455, 533],
       [904, 195, 131,  67, 876],
       [729, 117, 890, 167, 541],
       [678, 234, 661, 200, 753],
       [592, 163, 614, 114, 988]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
color = np.dtype([
    ('R', np.uint8),
    ('G', np.uint8),
    ('B', np.uint8),
    ('A', np.uint8)
])

colors = np.array((255, 0, 0, 128), dtype = color)

red = colors['R']
green = colors['G']
blue = colors['B']
alpha = colors['A']

print("RGBA Color:", color)
print("Red:", red)
print("Green:", green)
print("Blue:", blue)
print("Alpha:", alpha)

RGBA Color: [('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')]
Red: 255
Green: 0
Blue: 0
Alpha: 128


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
matrix1 = np.random.rand(5,3)
print(matrix1)
matrix2 = np.random.rand(3,2)
print("\n",matrix2)

print("\n",np.dot(matrix1, matrix2))
#print(matrix1 * matrix2)

[[0.12521372 0.23630688 0.19841595]
 [0.94886317 0.69204743 0.81715734]
 [0.26373976 0.61301176 0.67932649]
 [0.12429403 0.91380393 0.06823858]
 [0.5944051  0.32811769 0.33420622]]

 [[0.43108948 0.34766912]
 [0.29472239 0.59932349]
 [0.76653768 0.49209267]]

 [[0.27571654 0.28279624]
 [1.2393887  1.14676785]
 [0.81509308 0.79337811]
 [0.37520776 0.62445706]
 [0.60912708 0.56776537]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
x = np.arange(11)
x[(3 < x) & (x <= 8)] *= -1
print(x)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1)) # --> 9   This line uses Python's built-in sum
from numpy import *     # --> '*' it will includes all the functions, classes, and variables defined in NumPy
print(sum(range(5),-1)) # --> 10  This line uses NumPy's sum function

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z**Z        # --> legal
2 << Z >> 2 # --> legal
Z <- Z      # --> legal
1j*Z        # --> legal
Z/1/1       # --> legal
Z<Z>Z       # --> not legal

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
np.array(0) / np.array(0)                      # --> nan
np.array(0) // np.array(0)                     # --> 0
np.array([np.nan]).astype(int).astype(float)   # --> arr([nan])

#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
def round_array(x,y):
    return np.round(x,y)

test = np.array([32.11, 51.5, 0.112])
print(round_array(test,0))

[32. 52.  0.]


#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
x = np.array([1, 2, 2, 3, 4, 4, 4, 5, 6, 6, 7])

common_values = np.unique(x)

print(common_values)

[1 2 3 4 5 6 7]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
warn = np.seterr(all='ignore')
z = np.ones(5) / 0
print(z)

[inf inf inf inf inf]


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
# no its False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [ ]:
import datetime
today = datetime.date.today()

yesterday = today - datetime.timedelta(days=1)
tomorrow = today + datetime.timedelta(days=1)

print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)

Yesterday: 2023-09-24
Today: 2023-09-25
Tomorrow: 2023-09-26


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
import datetime

start_date = datetime.date(2016, 7, 1)
end_date = datetime.date(2016, 7, 31)

date_range = np.arange(start_date, end_date + datetime.timedelta(days=1), datetime.timedelta(days=1))

for date in date_range:
    print(date)

2016-07-01T00:00:00.000000
2016-07-02T00:00:00.000000
2016-07-03T00:00:00.000000
2016-07-04T00:00:00.000000
2016-07-05T00:00:00.000000
2016-07-06T00:00:00.000000
2016-07-07T00:00:00.000000
2016-07-08T00:00:00.000000
2016-07-09T00:00:00.000000
2016-07-10T00:00:00.000000
2016-07-11T00:00:00.000000
2016-07-12T00:00:00.000000
2016-07-13T00:00:00.000000
2016-07-14T00:00:00.000000
2016-07-15T00:00:00.000000
2016-07-16T00:00:00.000000
2016-07-17T00:00:00.000000
2016-07-18T00:00:00.000000
2016-07-19T00:00:00.000000
2016-07-20T00:00:00.000000
2016-07-21T00:00:00.000000
2016-07-22T00:00:00.000000
2016-07-23T00:00:00.000000
2016-07-24T00:00:00.000000
2016-07-25T00:00:00.000000
2016-07-26T00:00:00.000000
2016-07-27T00:00:00.000000
2016-07-28T00:00:00.000000
2016-07-29T00:00:00.000000
2016-07-30T00:00:00.000000
2016-07-31T00:00:00.000000


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
A = np.array([1, 2, 3],dtype=np.float64)
B = np.array([4, 5, 6],dtype=np.float64)


A *= -0.5
A += B

print(A)

[3.5 4.  4.5]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [ ]:
x = np.random.uniform(0,10,10)
print(x)
print()
print (x-x%1)
print()
print (np.floor(x))
print()
print (x.astype(int))
print()
print (np.trunc(x))

[1.25181845 4.64771423 1.328676   8.44361218 3.51722112 6.60527477
 6.33741979 1.43697703 2.99760555 7.96394917]

[1. 4. 1. 8. 3. 6. 6. 1. 2. 7.]

[1. 4. 1. 8. 3. 6. 6. 1. 2. 7.]

[1 4 1 8 3 6 6 1 2 7]

[1. 4. 1. 8. 3. 6. 6. 1. 2. 7.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
x = np.zeros((5,5))
x += np.arange(5)
print(x)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [ ]:
x = np.array([0,1,2,3,4])

z = np.tile(x,(5,1))
z

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [ ]:
import random
def generator(d =[]):
  for i in range(10):
    d.append(random.randint(1,100))

d = []
generator(d)

x = np.array(d)
print(x)

[29 29 16 27 94 98 59 85 38 68]


In [ ]:
def integer_generator():
    for i in range(10):
        yield i

my_generator = integer_generator()

x = np.array(list(my_generator))

print(x)


[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [ ]:
vector = np.linspace(0, 1, 10, endpoint=False)[1:]

print(vector)

[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
x = (np.random.rand(1, 10)*100).astype(int)
x.sort()
print(x)

[[15 21 36 46 64 69 73 74 78 91]]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [ ]:
from numba import jit
import numpy as np

@jit(nopython=True)
def custom_sum(arr):
    result = 0.0
    for val in arr:
        result += val
    return result

arr = np.array([1.0, 2.0, 3.0])
result = custom_sum(arr)
print(result)

6.0


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [ ]:
x = np.random.randint(1,5,5)
y = np.random.randint(1,5,5)
print(x)
print(y,"\n")
are_equal = np.array_equal(x,y)

if are_equal:
   print("the two array is equal")
else:
   print("the two array is not equal")

[4 4 4 3 3]
[2 4 2 4 4] 

the two array is not equal


#### 43. Make an array immutable (read-only) (★★☆)

In [ ]:
mutable_array = np.array([1, 2, 3])

immutable_array = mutable_array.copy()
immutable_array.flags.writeable = False

In [ ]:
immutable_array = np.array([1, 2, 3, 4, 5])
immutable_array.flags.writeable = False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [ ]:
np.random.seed(0)
cartesian_coordinates = np.random.rand(10, 2)

r = np.sqrt(cartesian_coordinates[:, 0]**2 + cartesian_coordinates[:, 1]**2)
theta = np.arctan2(cartesian_coordinates[:, 1], cartesian_coordinates[:, 0])

polar_coordinates = np.column_stack((r, theta))

print("Cartesian Coordinates:")
print(cartesian_coordinates)
print("\nPolar Coordinates:")
print(polar_coordinates)

Cartesian Coordinates:
[[0.5488135  0.71518937]
 [0.60276338 0.54488318]
 [0.4236548  0.64589411]
 [0.43758721 0.891773  ]
 [0.96366276 0.38344152]
 [0.79172504 0.52889492]
 [0.56804456 0.92559664]
 [0.07103606 0.0871293 ]
 [0.0202184  0.83261985]
 [0.77815675 0.87001215]]

Polar Coordinates:
[[0.90149437 0.91627198]
 [0.81254007 0.73500704]
 [0.77243938 0.99027074]
 [0.99334871 1.1146216 ]
 [1.03714672 0.37869482]
 [0.95213359 0.58894485]
 [1.08600357 1.02035952]
 [0.11241724 0.88679866]
 [0.83286529 1.54651823]
 [1.16723994 0.84107236]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [ ]:
x = np.random.randint(1,11,10)
print(x)
c = np.argmax(x)
x[c] = 0
print(x)

[ 8  6  6  1  2  6 10  4  1  6]
[8 6 6 1 2 6 0 4 1 6]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [ ]:
num_points = 10

x = np.linspace(0, 1, num_points)
y = np.linspace(0, 1, num_points)

x_grid, y_grid = np.meshgrid(x, y)

structured_array = np.column_stack((x_grid.ravel(), y_grid.ravel()))

print("Structured Array:")
print(structured_array)

Structured Array:
[[0.         0.        ]
 [0.11111111 0.        ]
 [0.22222222 0.        ]
 [0.33333333 0.        ]
 [0.44444444 0.        ]
 [0.55555556 0.        ]
 [0.66666667 0.        ]
 [0.77777778 0.        ]
 [0.88888889 0.        ]
 [1.         0.        ]
 [0.         0.11111111]
 [0.11111111 0.11111111]
 [0.22222222 0.11111111]
 [0.33333333 0.11111111]
 [0.44444444 0.11111111]
 [0.55555556 0.11111111]
 [0.66666667 0.11111111]
 [0.77777778 0.11111111]
 [0.88888889 0.11111111]
 [1.         0.11111111]
 [0.         0.22222222]
 [0.11111111 0.22222222]
 [0.22222222 0.22222222]
 [0.33333333 0.22222222]
 [0.44444444 0.22222222]
 [0.55555556 0.22222222]
 [0.66666667 0.22222222]
 [0.77777778 0.22222222]
 [0.88888889 0.22222222]
 [1.         0.22222222]
 [0.         0.33333333]
 [0.11111111 0.33333333]
 [0.22222222 0.33333333]
 [0.33333333 0.33333333]
 [0.44444444 0.33333333]
 [0.55555556 0.33333333]
 [0.66666667 0.33333333]
 [0.77777778 0.33333333]
 [0.88888889 0.33333333]
 [1.   

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [ ]:
X = np.array([1.0, 2.0, 3.0])
Y = np.array([0.0, 2.5, 4.0])

num_x = len(X)
num_y = len(Y)
C = np.empty((num_x, num_y))

for i in range(num_x):
    for j in range(num_y):
        C[i, j] = 1.0 / (X[i] - Y[j])

print(C)

[[ 1.         -0.66666667 -0.33333333]
 [ 0.5        -2.         -0.5       ]
 [ 0.33333333  2.         -1.        ]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [ ]:
import numpy as np

scalar_types = [np.int8, np.uint8, np.int16, np.uint16, np.int32, np.uint32,
                np.int64, np.uint64, np.float16, np.float32, np.float64, np.complex64, np.complex128]

for dtype in scalar_types:
    min_val = np.iinfo(dtype).min if np.issubdtype(dtype, np.integer) else np.finfo(dtype).min
    max_val = np.iinfo(dtype).max if np.issubdtype(dtype, np.integer) else np.finfo(dtype).max
    print(f"Type: {dtype}")
    print(f"Minimum: {min_val}")
    print(f"Maximum: {max_val}")
    print()

Type: <class 'numpy.int8'>
Minimum: -128
Maximum: 127

Type: <class 'numpy.uint8'>
Minimum: 0
Maximum: 255

Type: <class 'numpy.int16'>
Minimum: -32768
Maximum: 32767

Type: <class 'numpy.uint16'>
Minimum: 0
Maximum: 65535

Type: <class 'numpy.int32'>
Minimum: -2147483648
Maximum: 2147483647

Type: <class 'numpy.uint32'>
Minimum: 0
Maximum: 4294967295

Type: <class 'numpy.int64'>
Minimum: -9223372036854775808
Maximum: 9223372036854775807

Type: <class 'numpy.uint64'>
Minimum: 0
Maximum: 18446744073709551615

Type: <class 'numpy.float16'>
Minimum: -65504.0
Maximum: 65504.0

Type: <class 'numpy.float32'>
Minimum: -3.4028234663852886e+38
Maximum: 3.4028234663852886e+38

Type: <class 'numpy.float64'>
Minimum: -1.7976931348623157e+308
Maximum: 1.7976931348623157e+308

Type: <class 'numpy.complex64'>
Minimum: -3.4028234663852886e+38
Maximum: 3.4028234663852886e+38

Type: <class 'numpy.complex128'>
Minimum: -1.7976931348623157e+308
Maximum: 1.7976931348623157e+308



#### 49. How to print all the values of an array? (★★☆)

In [ ]:
x = np.array([1,2,3,4,5,6,7,8,9])

print(x)

[1 2 3 4 5 6 7 8 9]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [ ]:
x = np.array([1.6,2.8,3.5,4.3,5.9,6.6,7.5,10.1])

scalar = 6.0

closest_greater = float('inf')
closest_less = float('-inf')

for i in range(len(x)):

  if x[i] == scalar:
    print(f"the closest value is {x[i]}")
    break

  elif x[i] > scalar and x[i] < closest_greater:
    closest_greater = x[i]

  elif x[i] < scalar and x[i] > closest_less:
        closest_less = x[i]

if ((closest_greater < float('inf')) - scalar ) < ((closest_less > float('-inf')) - scalar ) :
    print(f"The closest value greater than scalar is {closest_greater}")

else:
    print(f"The closest value less than scalar is {closest_less}")


The closest value less than scalar is 5.9


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [ ]:
array = np.zeros((3,), dtype=[('x', float), ('y', float),
       ('r', int), ('g', int), ('b',int)])

array['x'] = np.random.rand(3)
array['y'] = np.random.rand(3)
array['r'] = np.random.randint(0, 255, 3)
array['g'] = np.random.randint(0, 255, 3)
array['b'] = np.random.randint(0, 255, 3)
print(array)

[(0.96073088, 0.72768885, 177, 184, 114)
 (0.35534569, 0.255819  , 207,  10,  92)
 (0.13901071, 0.68479873,  81, 199,  76)]


In [ ]:
dtype = np.dtype([
    ('position', [('x', float), ('y', float)]),
    ('color', [('r', int), ('g', int), ('b', int)])
])

data = np.array([
    ((1.0, 2.0), (255, 0, 0)),
    ((3.5, 4.5), (0, 128, 255)),
], dtype=dtype)

first_entry = data[0]
position = first_entry['position']
color = first_entry['color']

print("Position:", position)
print("Color:", color)

Position: (1., 2.)
Color: (255, 0, 0)


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [ ]:
np.random.seed(0)
coordinates = np.random.rand(100, 2)

differences = coordinates[:, np.newaxis] - coordinates
distances = np.linalg.norm(differences, axis=2)

print("Pairwise Distances:")
print(distances)

Pairwise Distances:
[[0.         0.1786471  0.14306129 ... 0.29476183 0.56184    0.5654225 ]
 [0.1786471  0.         0.20562852 ... 0.14721688 0.47464981 0.55582212]
 [0.14306129 0.20562852 0.         ... 0.35206592 0.43796338 0.42237997]
 ...
 [0.29476183 0.14721688 0.35206592 ... 0.         0.5639395  0.68382195]
 [0.56184    0.47464981 0.43796338 ... 0.5639395  0.         0.24721062]
 [0.5654225  0.55582212 0.42237997 ... 0.68382195 0.24721062 0.        ]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [ ]:
x = np.array([3.545,5.49895,646.549,5.4598],dtype = np.float32)

x = x.view(np.int32)

print(x)

[1080222024 1085273958 1143055139 1085191854]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO

s= StringIO("""1, 2, 3, 4, 5\n
               6,  ,  , 7, 8\n
               ,  , 9,10,11\n""")

z = np.genfromtxt(s,delimiter=",",dtype=np.int)

print(z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


<ipython-input-23-e24a5e02988f>:7: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  z = np.genfromtxt(s,delimiter=",",dtype=np.int)


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [ ]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

for index, value in np.ndenumerate(x):
    print(f"Index {index}: Value {value}")

Index (0, 0): Value 1
Index (0, 1): Value 2
Index (0, 2): Value 3
Index (1, 0): Value 4
Index (1, 1): Value 5
Index (1, 2): Value 6
Index (2, 0): Value 7
Index (2, 1): Value 8
Index (2, 2): Value 9


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [ ]:
size = (2,2)
sigma = 1.0

x, y = np.meshgrid(np.linspace(-5, 5, size[0]), np.linspace(-5, 5, size[1]))

gaussian_array = np.exp(-(x**2 + y**2) / (2 * sigma**2))

gaussian_array /= np.sum(gaussian_array)

print(gaussian_array)

[[0.25 0.25]
 [0.25 0.25]]


#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [ ]:
rows, cols = 5, 5
array_size = (rows, cols)

x = np.zeros(array_size)

p = 5

random_coords = np.random.randint(0, 5, size=(p, 2))

for row, col in random_coords:
    x[row, col] = 1

print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [ ]:
matrix = np.array([[1, 2, 3],
                  [4, 5, 6]])


row_means = np.mean(matrix, axis=1)

centered_matrix = matrix - row_means[:, np.newaxis]

print(centered_matrix)

[[-1.  0.  1.]
 [-1.  0.  1.]]


#### 59. How to sort an array by the nth column? (★★☆)

In [ ]:
array = np.array([[3, 1, 4],
                  [1, 5, 9],
                  [2, 6, 5]])

n = 1

sorted_indices = np.argsort(array[:, n])

sorted_array = array[sorted_indices]

print(sorted_array)

[[3 1 4]
 [1 5 9]
 [2 6 5]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [ ]:
array = np.array([[0, 1, 0],
                  [0, 0, 0],
                  [0, 1, 0]])

null_value = 0

null_columns = np.all(array == null_value, axis=0)

if np.any(null_columns):
    print("The array has null columns.")
else:
    print("The array does not have null columns.")

The array has null columns.


#### 61. Find the nearest value from a given value in an array (★★☆)

In [ ]:
array = np.array([2, 4, 7, 12, 15, 18, 21])

given_value = 10

x = np.abs(array - given_value)

c = np.argmin(x)

nearest_value = array[c]

print(f"Given value: {given_value}")
print(f"Nearest value: {nearest_value}")
print(f"Index of nearest value: {c}")

Given value: 10
Nearest value: 12
Index of nearest value: 3


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [ ]:
array1 = np.array([[1, 2, 3]])
array2 = np.array([[4], [5], [6]])

assert array1.shape == (1, 3)
assert array2.shape == (3, 1)

sum_result = np.zeros((1, 3))

for i in range(array1.shape[0]):
    for j in range(array1.shape[1]):
        sum_result[i, j] = array1[i, j] + array2[j, i]

print(sum_result)

[[5. 7. 9.]]


#### 63. Create an array class that has a name attribute (★★☆)

In [ ]:
class NamedArray(np.ndarray):
    def __new__(cls, input_array, name="Unnamed Array"):
        obj = np.asarray(input_array).view(cls)
        obj.name = name
        return obj

    def __array_finalize__(self, obj):
        if obj is None:
            return
        self.name = getattr(obj, 'name', 'Unnamed Array')

data = [1, 2, 3, 4, 5]
named_array = NamedArray(data, name="My Named Array")

print("Array Name:", named_array.name)

print("Sum:", np.sum(named_array))

Array Name: My Named Array
Sum: 15


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [2]:
given_vector = np.array([1, 2, 3, 4, 5])
indices_to_add_1 = np.array([1, 2, 3, 3, 4])

result_vector = given_vector.copy()

indices_added = set()

for index in indices_to_add_1:
    if index not in indices_added:
        result_vector[index] += 1
        indices_added.add(index)

print(result_vector)

[1 3 4 5 6]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [3]:
X = np.array([1, 2, 3, 4, 5])
I = np.array([1, 2, 0, 1, 3])

F_length = max(I) + 1

F = np.zeros(F_length)

for i, index in enumerate(I):
    F[index] += X[i]

print(F)

[3. 5. 2. 5.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [4]:
w, h = 10, 10
image = np.random.randint(0, 256, (w, h, 3), dtype=np.uint8)

pixels = image.reshape((-1, 3))

unique_colors = set(map(tuple, pixels))

num_unique_colors = len(unique_colors)

print(f"Number of unique colors: {num_unique_colors}")

Number of unique colors: 100


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [5]:
x = np.random.randint(0, 10, size=(2, 3, 4, 5))

sum_over_last_two_axes = np.sum(x, axis=(-2, -1))

print("Original 4D array:")
print(x)
print("\nSum over the last two axes:")
print(sum_over_last_two_axes)

Original 4D array:
[[[[8 2 9 9 3]
   [0 6 0 0 7]
   [4 8 1 7 0]
   [6 1 0 7 6]]

  [[6 9 2 9 4]
   [4 6 3 8 1]
   [6 7 0 7 0]
   [3 6 3 8 4]]

  [[7 5 9 7 8]
   [4 2 1 2 7]
   [2 5 0 5 2]
   [0 4 8 1 4]]]


 [[[6 1 7 0 9]
   [6 5 0 6 0]
   [6 9 4 1 9]
   [5 2 3 9 3]]

  [[6 1 5 5 9]
   [5 7 6 7 0]
   [1 0 4 5 9]
   [3 7 8 2 3]]

  [[4 9 8 9 0]
   [3 0 4 5 9]
   [8 0 0 8 4]
   [5 6 2 3 5]]]]

Sum over the last two axes:
[[84 96 83]
 [91 93 92]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [6]:
D = np.array([1, 2, 3, 4, 5, 6, 7, 8])
S = np.array([0, 1, 0, 1, 0, 1, 0, 1])

unique_indices = np.unique(S)

subset_means = [np.mean(D[S == idx]) for idx in unique_indices]

print("One-dimensional vector D:")
print(D)
print("\nSubset index vector S:")
print(S)
print("\nSubset means:")
print(subset_means)

One-dimensional vector D:
[1 2 3 4 5 6 7 8]

Subset index vector S:
[0 1 0 1 0 1 0 1]

Subset means:
[4.0, 5.0]


#### 69. How to get the diagonal of a dot product? (★★★)

In [7]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

dot_product = np.dot(A, B)

diagonal = np.diagonal(dot_product)

print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)
print("\nDot Product of A and B:")
print(dot_product)
print("\nDiagonal of the Dot Product:")
print(diagonal)

Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Dot Product of A and B:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Diagonal of the Dot Product:
[30 69 90]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [9]:
original_vector = np.array([1, 2, 3, 4, 5])

consecutive_zeros = 3

new_length = len(original_vector) + (len(original_vector) - 1) * consecutive_zeros

new_vector = np.zeros(new_length, dtype=original_vector.dtype)

new_vector[::4] = original_vector

print(new_vector)

[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)